apps/lista_negra/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('lista_negra', views.Lista_Negra_View)


urlpatterns = [
	url('', include(router.urls))
]

apps/revision/urls.py
from django.conf.urls import url

from views import index, revision_view, lista_revision, editar_revision, eliminar_revision

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', revision_view, name='revision_crear'),
    url(r'^lista$', lista_revision, name='revision_lista'),
    url(r'^editar/(?P<id_revisar>\d+)/$', editar_revision, name='revision_editar'),
    url(r'^eliminar/(?P<id_revisar>\d+)/$', eliminar_revision, name='revision_eliminar'),
]

lista_negra/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^revision/', include('apps.revision.urls', namespace="revision")),
    url(r'^lista_negra/', include('apps.lista_negra.urls', namespace="lista_negra")),
]

apps/lista_negra/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Lista_Negra(models.Model):
	msisdn = models.CharField(max_length=12)
	fecha_ingreso = models.DateTimeField()
	razon_ingreso = models.CharField(max_length=320)
	operadora = models.CharField(max_length=25)

	def __str__(self):
		return self.msisdn

apps/revision/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class revisar(models.Model):
	msisdn = models.CharField(max_length=12)
	fecha_ingreso = models.DateField()
	razon_ingreso = models.CharField(max_length=320)
	operadora = models.CharField(max_length=25)

apps/revision/forms.py
from django import forms
from models import revisar

class revisionForm(forms.ModelForm):

	class Meta:
		model = revisar

		fields = [
			'msisdn',
			'fecha_ingreso',
			'razon_ingreso',
			'operadora',
		]
		labels = {
			'msisdn': 'Msisdn',
			'fecha_ingreso': 'Fecha Ingreso',
			'razon_ingreso': 'Razon Ingreso',
			'operadora': 'Operadora',
		}
		widgets = {
			'msisdn': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_ingreso': forms.DateInput(attrs={'class':'form-control'}),
			'razon_ingreso': forms.TextInput(attrs={'class':'form-control'}),
			'operadora': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/lista_negra/views.py
import json

from django.shortcuts import render
from django.http import HttpResponse

from rest_framework import viewsets
from .models import Lista_Negra
from .serializers import Lista_Negra_Serializer


class Lista_Negra_View(viewsets.ModelViewSet):
	queryset = Lista_Negra.objects.all()
	serializer_class = Lista_Negra_Serializer







	

apps/revision/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse

from forms import revisionForm
from models import revisar

# Create your views here.

def index(request):
	return render(request, 'revision/index.html')


def revision_view(request):
	if request.method == 'POST':
		form = revisionForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('revision:index')
	else: 
		form = revisionForm()

	return render(request, 'revision/formulario.html', {'form': form})


def lista_revision(request):
	revisar1 = revisar.objects.all().order_by('id')
	contexto = {'lista_revisar': revisar1}
	return render(request, 'revision/lista_revision.html', contexto)


def editar_revision(request, id_revisar):
	revisar1 = revisar.objects.get(id=id_revisar)
	if request.method == 'GET':
		form = revisionForm(instance=revisar1)
	else:
		form = revisionForm(request.POST, instance=revisar1)
		if form.is_valid():
			form.save()
		return redirect('revision:revision_lista')
	return render(request, 'revision/formulario.html', {'form':form})

def eliminar_revision(request, id_revisar):
	revisar1 = revisar.objects.get(id=id_revisar)
	contexto = {'lista_eliminar': revisar1}
	if request.method == 'POST':
		revisar1.delete()
		return redirect('revision:revision_lista')
	return render(request, 'revision/eliminar_revision.html', contexto)

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %} Document {% endblock %}</title>
</head>
<body>

{% block prueba %}

<h1>Litera</h1>
<h2>¡¡Boostrap!!</h2>
<div>
    <a href="#" class="btn btn-default">Default</a>
    <a href="#" class="btn btn-primary">Primary</a>
    <a href="#" class="btn btn-success">Success</a>
    <a href="#" class="btn btn-info">Info</a>
    <a href="#" class="btn btn-warning">Warning</a>
    <a href="#" class="btn btn-danger">Danger</a>
</div>

{% endblock%}

<br>

{% block content %}

{% endblock %}

<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
	
</body>
</html>

templates/revision/eliminar_revision.html
{% extends 'base/base.html' %}


{% block content %}
<form method="POST">
	{% csrf_token %}
    <h3>¿Desea eliminar el registro {{ lista_eliminar.id }}?</h3>
	<button class="btn btn-danger" type="submit">Eliminar</button>
	<a class="btn btn-secondary" href="{% url 'revision:revision_lista' %}">Cancelar</a>
</form>
{% endblock %}

templates/revision/formulario.html
{% extends 'base/base.html' %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/revision/index.html
{%extends 'base/base.html'%}

{% block title %}

Revision de Lista de Negra

{% endblock %}

{% block prueba %}
<h4> Pagina Principal </h4> 
{% endblock %}

templates/revision/lista_revision.html
{% extends 'base/base.html' %}

{% block prueba %}

<table class="table table-bordered">
	<tr>
		<th>#</th>
		<th>Msisdn</th>
		<th>Fecha Ingreso</th>
		<th>Razon Ingreso</th>
		<th>Operadora</th>
		<th>Acciones</th>
	</tr>
	{%if lista_revisar %}
	{% for lista in lista_revisar %}
	<tr>
		<td>{{ lista.id }}</td>
		<td>{{ lista.msisdn }}</td>
		<td>{{ lista.fecha_ingreso }}</td>
		<td>{{ lista.razon_ingreso }}</td>
		<td>{{ lista.operadora }}</td>
		<td>
			<a class="btn btn-primary" href="{% url 'revision:revision_editar' lista.id %}">Editar</a>
			<a class="btn btn-danger" href="{% url 'revision:revision_eliminar' lista.id %}">Eliminar</a>
		</td>
	</tr>
	{% endfor %}
	{% else %}
	<h1>No hay registros</h1>
	{% endif %}

</table>

{% endblock %}